# Generated by Django 4.1.4 on 2022-12-14 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('Cno', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='课程编号')),
                ('Cname', models.CharField(max_length=24, verbose_name='课程名称')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Sno', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='学号')),
                ('Sname', models.CharField(max_length=24, verbose_name='姓名')),
                ('Ssex', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('Birthdate', models.DateField(verbose_name='出生日期')),
                ('AdmissionDate', models.DateField(verbose_name='入学时间')),
                ('Sdept', models.CharField(max_length=32, verbose_name='专业名称')),
                ('Sclass', models.CharField(max_length=64, verbose_name='班级')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('Tno', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='编号')),
                ('Tname', models.CharField(max_length=24, verbose_name='姓名')),
                ('Tsex', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('Birthdate', models.DateField(verbose_name='出生日期')),
                ('EntryDate', models.DateField(verbose_name='入职时间')),
                ('Phone', models.CharField(max_length=11, verbose_name='联系电话')),
            ],
        ),
        migrations.CreateModel(
            name='StudAccount',
            fields=[
                ('Saccount', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sapp.student', verbose_name='账号')),
                ('Spwd', models.CharField(max_length=32, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='TeacAccount',
            fields=[
                ('Taccount', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sapp.teacher', verbose_name='账号')),
                ('Tpwd', models.CharField(max_length=32, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('SCid', models.AutoField(primary_key=True, serialize=False)),
                ('Grade', models.IntegerField(verbose_name='成绩')),
                ('Cno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sapp.course', verbose_name='课程编号')),
                ('Sno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sapp.student', verbose_name='学生学号')),
            ],
            options={
                'verbose_name': '学生成绩信息',
                'verbose_name_plural': '学生成绩信息',
            },
        ),
        migrations.CreateModel(
            name='Schedulu',
            fields=[
                ('Sid', models.AutoField(primary_key=True, serialize=False)),
                ('Cno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sapp.course', verbose_name='课程编号')),
                ('Tno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sapp.teacher', verbose_name='教师编号')),
            ],
            options={
                'verbose_name': '教师课表',
                'verbose_name_plural': '教师课表',
            },
        ),
    ]
